Traceback (most recent call last):
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tom/miniconda3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def extreme_value_test_1(extreme_value=M):
    '''
    Extreme value test 1: 
    
    Wards, Em Surgery, other hospitals, x-ray, electives have their inter-arrival time is
    set to $M$ a very large number
    Expected result: The only type of patient to arrive to the model is "Accident and Emergency."
    '''
    mod_interarrival_means = [22.72] + [extreme_value] * 5 
    experiment = Experiment(interarrival_means=mod_interarrival_means)
    run_test(experiment)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m [38;5;28;01mdef[39;00m [38;5;21mextreme_value_test_1[39m(extreme_value[38;5;241m=[39m[43mM[49m):
[1;32m      2[0m [38;5;250m    [39m[38;5;124;03m'''[39;00m
[1;32m      3[0m [38;5;124;03m    Extreme value test 1: [39;00m
[1;32m      4[0m [38;5;124;03m    [39;00m
[0;32m   (...)[0m
[1;32m      7[0m [38;5;124;03m    Expected result: The only type of patient to arrive to the model is "Accident and Emergency."[39;00m
[1;32m      8[0m [38;5;124;03m    '''[39;00m
[1;32m      9[0m     mod_interarrival_means [38;5;241m=[39m [[38;5;241m22.72[39m] [38;5;241m+[39m [extreme_value] [38;5;241m*[39m [38;5;241m5[39m 

[0;31mNameError[0m: name 'M' is not defined

