Traceback (most recent call last):
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tom/miniforge3/envs/gen_simpy/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
results_collection_test1()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[26], line 1[0m
[0;32m----> 1[0m [43mresults_collection_test1[49m[43m([49m[43m)[49m

Cell [0;32mIn[25], line 30[0m, in [0;36mresults_collection_test1[0;34m(audit_interval)[0m
[1;32m     27[0m acu_experiment [38;5;241m=[39m AcuteStrokeUnit(env, default_experiment_params, rehab_unit)
[1;32m     29[0m [38;5;66;03m# Start the patient generators for each type of patient[39;00m
[0;32m---> 30[0m env[38;5;241m.[39mprocess([43macu_experiment[49m[38;5;241;43m.[39;49m[43mstroke_patient_generator[49m())
[1;32m     31[0m env[38;5;241m.[39mprocess(acu_experiment[38;5;241m.[39mtia_patient_generator())
[1;32m     32[0m env[38;5;241m.[39mprocess(acu_experiment[38;5;241m.[39mneuro_patient_generator())

[0;31mAttributeError[0m: 'AcuteStrokeUnit' object has no attribute 'stroke_patient_generator'

